### ISSUE TITLE
Can't start a template with a variable

### ISSUE THREAD

**Issue by sstone1** [accordproject/cicero#1]
Template:

`[{name}] agrees to spend [{amount}] conga coins on swag`

Error:

```
error:  Error: unrecognized token: {"literal":""}
    at buildToken (/Users/sstone1/.nvm/versions/node/v8.9.0/lib/node_modules/cicero-cli/node_modules/nearley/lib/compile.js:160:15)
    at buildRule (/Users/sstone1/.nvm/versions/node/v8.9.0/lib/node_modules/cicero-cli/node_modules/nearley/lib/compile.js:95:25)
    at produceRules (/Users/sstone1/.nvm/versions/node/v8.9.0/lib/node_modules/cicero-cli/node_modules/nearley/lib/compile.js:84:24)
    at Compile (/Users/sstone1/.nvm/versions/node/v8.9.0/lib/node_modules/cicero-cli/node_modules/nearley/lib/compile.js:73:13)
    at Function.compileGrammar (/Users/sstone1/.nvm/versions/node/v8.9.0/lib/node_modules/cicero-cli/node_modules/cicero-core/lib/template.js:364:39)
    at Template.setGrammar (/Users/sstone1/.nvm/versions/node/v8.9.0/lib/node_modules/cicero-cli/node_modules/cicero-core/lib/template.js:125:36)
    at Template.buildGrammar (/Users/sstone1/.nvm/versions/node/v8.9.0/lib/node_modules/cicero-cli/node_modules/cicero-core/lib/template.js:275:14)
    at Function.fromDirectory (/Users/sstone1/.nvm/versions/node/v8.9.0/lib/node_modules/cicero-cli/node_modules/cicero-core/lib/template.js:787:22)
    at Function.execute (/Users/sstone1/.nvm/versions/node/v8.9.0/lib/node_modules/cicero-cli/lib/commands.js:67:25)
    at Object.require.command.command [as handler] (/Users/sstone1/.nvm/versions/node/v8.9.0/lib/node_modules/cicero-cli/index.js:57:25)
```

Putting any character, including whitespace, before the variable works fine.

**Comment by dselman** [comment]
Fixed.
