### ISSUE TITLE
Template.getRequestTypes fails if there is no logic

### ISSUE THREAD

**Issue by dselman** [accordproject/cicero#149]
It is *valid* for a Cicero template to not have any logic files. We need to check that all similar operations (state, events, response) also work if there is no logic.

TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at Template.getRequestTypes (/Users/dselman/dev/cicero-template-library/node_modules/@accordproject/cicero-core/lib/template.js:1192:14)
    at templatePageGenerator (/Users/dselman/dev/cicero-template-library/run.js:346:30)
    at buildTemplates (/Users/dselman/dev/cicero-template-library/run.js:235:27)
    at <anonymous>

**Comment by dselman** [comment]
Fixed.
