### ISSUE TITLE
Line breaks shouldn't fail parsing

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/cicero#197]
As per a thread in the AP #technology-wg channel. It is confusing to users who edit files with editors that automatically change the line break format.

The behaviour can be replicated by opening the `helloworld` sample.txt file in VSCode, and changing the line break format from `LF` to `CRLF` and saving.

Parsing the original sample works, parsing the changed sample fails with: 
```
mattmbp:helloworld matt$ cicero parse
14:09:32 - info: Using current directory as template folder
14:09:32 - info: Loading a default sample.txt file.
14:09:33 - error: invalid syntax at line 1 col 43:

  Name of the person to greet: "Fred Blogs".
                                            ^
Unexpected "\r"

Error: invalid syntax at line 1 col 43:

  Name of the person to greet: "Fred Blogs".
                                            ^
Unexpected "\r"

    at Parser.feed (/Users/matt/.nvm/versions/node/v8.11.1/lib/node_modules/@accordproject/cicero-cli/node_modules/nearley/lib/nearley.js:317:27)
    at Clause.parse (/Users/matt/.nvm/versions/node/v8.11.1/lib/node_modules/@accordproject/cicero-cli/node_modules/@accordproject/cicero-core/lib/templateinstance.js:97:16)
    at Template.fromDirectory.then (/Users/matt/.nvm/versions/node/v8.11.1/lib/node_modules/@accordproject/cicero-cli/lib/commands.js:54:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
14:09:33 - info: undefined

```

**Comment by jeromesimeon** [comment]
Fixed in Cicero 0.13.5

**Comment by lamqson** [comment]
I just tried it on 0.13.5. It still broken:
```
Sons-MacBook-Pro:cicero sonlam$ cat sample.txt
Name of the person to greet: "Fred Blogs".
Thank you!
Sons-MacBook-Pro:cicero sonlam$ cicero --version
0.13.5
Sons-MacBook-Pro:cicero sonlam$ cicero parse --template helloworld@0.11.1.cta --sample sample.txt
4:53:46 PM - error: invalid syntax at line 3 col 0:

  
  ^
Unexpected "\n"

Sons-MacBook-Pro:cicero sonlam$
```

**Comment by jeromesimeon** [comment]
@lamqson See my answer to that same comment in #219 

You most likely have an extra new line at the end of your sample (some editors add new lines on save, so you may want to check the configuration for your editor as well).

```
bash-3.2$ cicero --version
0.13.5
bash-3.2$ cat sample.txt 
Name of the person to greet: "Fred Blogs".
Thank you!bash-3.2$ cicero parse
10:03:34 - info: Using current directory as template folder
10:03:34 - info: Loading a default sample.txt file.
10:03:36 - info:
{
  "$class": "org.accordproject.helloworld.HelloWorldClause",
  "clauseId": "e5347c29-72b0-4b6d-a67d-530b715a7026",
  "name": "Fred Blogs"
}
bash-3.2$ 
```
